server.port=8080
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=listing-service
spring.cloud.gateway.routes[1].uri=lb://LISTING-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/classes/**,/enquiries/**

spring.cloud.gateway.routes[2].id=recommendation-service
spring.cloud.gateway.routes[2].uri=lb://RECOMMENDATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/recommendations/**